const regionToContinent = {
    'Northern America': 'North America',
    'Central America': 'North America',
    'South America': 'South America',
    'Western Europe': 'Europe',
    'Northern Europe': 'Europe',
    'Southern Europe': 'Europe',
    'Eastern Europe': 'Europe',
    'Europe': 'Europe',
    'Central Asia': 'Asia',
    'Eastern Asia': 'Asia',
    'Southern Asia': 'Asia',
    'South-Eastern Asia': 'Asia',
    'Western Asia': 'Asia',
    'Asia': 'Asia',
    'Northern Africa': 'Africa',
    'Western Africa': 'Africa',
    'Africa': 'Africa',
    'Oceania': 'Oceania',
    'World': 'Global',
    '': 'Unknown',
  };
  
  const countryToContinent = {
    'United States of America': 'North America',
    'Canada': 'North America',
    'Mexico': 'North America',
    'Belize': 'North America',
    'Brazil': 'South America',
    'Venezuela': 'South America',
    'Argentina': 'South America',
    'Colombia': 'South America',
    'Russia': 'Europe',
    'Germany': 'Europe',
    'United Kingdom': 'Europe',
    'France': 'Europe',
    'Spain': 'Europe',
    'Poland': 'Europe',
    'Hungary': 'Europe',
    'Austria': 'Europe',
    'Denmark': 'Europe',
    'Norway': 'Europe',
    'Estonia': 'Europe',
    'Greece': 'Europe',
    'India': 'Asia',
    'China': 'Asia',
    'Iran': 'Asia',
    'Iraq': 'Asia',
    'Japan': 'Asia',
    'Indonesia': 'Asia',
    'Jordan': 'Asia',
    'Pakistan': 'Asia',
    'Malaysia': 'Asia',
    'Saudi Arabia': 'Asia',
    'Lebanon': 'Asia',
    'Syria': 'Asia',
    'Kazakhstan': 'Asia',
    'Azerbaijan': 'Asia',
    'Turkey': 'Asia',
    'Qatar': 'Asia',
    'Cyprus': 'Asia',
    'United Arab Emirates': 'Asia',
    'Egypt': 'Africa',
    'Libya': 'Africa',
    'Nigeria': 'Africa',
    'South Africa': 'Africa',
    'Ghana': 'Africa',
    'Morocco': 'Africa',
    'Ethiopia': 'Africa',
    'Algeria': 'Africa',
    'Mali': 'Africa',
    'Niger': 'Africa',
    'Liberia': 'Africa',
    'Angola': 'Africa',
    'Burkina Faso': 'Africa',
    'South Sudan': 'Africa',
    'Australia': 'Oceania',
    '': 'Unknown',
  };
  
  function getContinent(region, country) {
    if (countryToContinent[country]) return countryToContinent[country];
    if (regionToContinent[region]) return regionToContinent[region];
    return 'Unknown';
  }
  
  export default getContinent;
  